# Generated by Django 4.0.5 on 2022-06-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='t_o_m',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
